export enum ActionType {
  INCREMENT_COUNT = 'INCREMENT_COUNT',
  RESET_COUNT = 'RESET_COUNT',

  // login
  UPDATE_LOGIN_INFO = 'UPDATE_LOGIN_INFO',
  CLEAR_LOGIN_INFO = 'CLEAR_LOGIN_INFO',

  // profile
  UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE',
  CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE',
}
