// source: proto/areaService.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var proto_area_pb = require('../proto/area_pb.js');
goog.object.extend(proto, proto_area_pb);
goog.exportSymbol('proto.pj.sakuchin.percussion.proto.GetAreaCityResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.repeatedFields_, null);
};
goog.inherits(proto.pj.sakuchin.percussion.proto.GetAreaCityResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.displayName = 'proto.pj.sakuchin.percussion.proto.GetAreaCityResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pj.sakuchin.percussion.proto.GetAreaCityResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    citiesList: jspb.Message.toObjectList(msg.getCitiesList(),
    proto_area_pb.City.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pj.sakuchin.percussion.proto.GetAreaCityResponse}
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pj.sakuchin.percussion.proto.GetAreaCityResponse;
  return proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pj.sakuchin.percussion.proto.GetAreaCityResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pj.sakuchin.percussion.proto.GetAreaCityResponse}
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_area_pb.City;
      reader.readMessage(value,proto_area_pb.City.deserializeBinaryFromReader);
      msg.addCities(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pj.sakuchin.percussion.proto.GetAreaCityResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCitiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto_area_pb.City.serializeBinaryToWriter
    );
  }
};


/**
 * repeated City cities = 1;
 * @return {!Array<!proto.pj.sakuchin.percussion.proto.City>}
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.prototype.getCitiesList = function() {
  return /** @type{!Array<!proto.pj.sakuchin.percussion.proto.City>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_area_pb.City, 1));
};


/**
 * @param {!Array<!proto.pj.sakuchin.percussion.proto.City>} value
 * @return {!proto.pj.sakuchin.percussion.proto.GetAreaCityResponse} returns this
*/
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.prototype.setCitiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pj.sakuchin.percussion.proto.City=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pj.sakuchin.percussion.proto.City}
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.prototype.addCities = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pj.sakuchin.percussion.proto.City, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pj.sakuchin.percussion.proto.GetAreaCityResponse} returns this
 */
proto.pj.sakuchin.percussion.proto.GetAreaCityResponse.prototype.clearCitiesList = function() {
  return this.setCitiesList([]);
};


goog.object.extend(exports, proto.pj.sakuchin.percussion.proto);
