// source: proto/error.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.pj.sakuchin.percussion.proto.PercussionApiError', null, global);
goog.exportSymbol('proto.pj.sakuchin.percussion.proto.PercussionApiError.ErrorCode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pj.sakuchin.percussion.proto.PercussionApiError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pj.sakuchin.percussion.proto.PercussionApiError.displayName = 'proto.pj.sakuchin.percussion.proto.PercussionApiError';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.prototype.toObject = function(opt_includeInstance) {
  return proto.pj.sakuchin.percussion.proto.PercussionApiError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pj.sakuchin.percussion.proto.PercussionApiError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.toObject = function(includeInstance, msg) {
  var f, obj = {
    errorcode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pj.sakuchin.percussion.proto.PercussionApiError}
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pj.sakuchin.percussion.proto.PercussionApiError;
  return proto.pj.sakuchin.percussion.proto.PercussionApiError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pj.sakuchin.percussion.proto.PercussionApiError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pj.sakuchin.percussion.proto.PercussionApiError}
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.pj.sakuchin.percussion.proto.PercussionApiError.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pj.sakuchin.percussion.proto.PercussionApiError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pj.sakuchin.percussion.proto.PercussionApiError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.ErrorCode = {
  UNKNOWN: 0,
  NO_TOKEN: 1,
  INVALID_FIREBASE_TOKEN: 2,
  USER_HAS_BEEN_ALREADY_REGISTERED: 3,
  DB_ERROR: 4,
  INVALID_PARAMETER: 5
};

/**
 * optional ErrorCode errorCode = 1;
 * @return {!proto.pj.sakuchin.percussion.proto.PercussionApiError.ErrorCode}
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.prototype.getErrorcode = function() {
  return /** @type {!proto.pj.sakuchin.percussion.proto.PercussionApiError.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.pj.sakuchin.percussion.proto.PercussionApiError.ErrorCode} value
 * @return {!proto.pj.sakuchin.percussion.proto.PercussionApiError} returns this
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pj.sakuchin.percussion.proto.PercussionApiError} returns this
 */
proto.pj.sakuchin.percussion.proto.PercussionApiError.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.pj.sakuchin.percussion.proto);
